### ISSUE TITLE
Hi, could you add a paper? Thanks

### ISSUE THREAD

**Issue by GodXuxilie** [corca-ai/awesome-llm-security#17]
Hi, could you please add the paper [An LLM can Fool Itself: A Prompt-Based Adversarial Attack](https://arxiv.org/abs/2310.13345#:~:text=This%20paper%20proposes%20an%20efficient,adversarial%20sample%20to%20fool%20itself.), which is related to adversarial robustness of the LLM? Thanks!

**Comment by L0Z1K** [comment]
Okay!
